language: php

php:
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --no-interaction --prefer-source

script:
  - composer validate --strict
  - vendor/bin/phpunit
